<?php

function alerta_theme_preprocess_page(&$variables) {

}

function alerta_theme_theme_suggestions_block_alter(array &$suggestions, array $variables) 
{ 
  // Block suggestions for custom block types. 
  if (isset($variables['elements']['content']['#block_content'])) { 
    array_splice($suggestions, 1, 0, 'block__type__' . $variables['elements']['content']['#block_content']->bundle()); 
  } 
}